feat: enable multiarch build
getsentry/sentry-kubernetes pull request #88
Opened 2024-03-07 14:38 UTC by nohant

Hello!

by adding the architecture in the GOARCH variable it should be compile faster and work better for the https://github.com/getsentry/sentry-kubernetes/issues/71

I didn't update the version of the various actions because maybe there is a motive for them to be that specific and I don't know.

Locally i tried `TARGETPLATFORM` and `TARGETARCH`

2024-03-08 17:27 UTC, tonyo requested changes
Thanks for the suggestion.

Doesn't seem to work in its current form (fails with `unsupported GOOS/GOARCH pair linux/linux/amd64` when testing locally), but might work with TARGETARCH.

2024-03-08 17:27 UTC, tonyo commented on Dockerfile
> +ARG TARGETPLATFORM
```suggestion
ARG TARGETARCH
```
Here and below; TARGETPLATFORM will be a full `linux/arm64`, and for GOARCH we'll need `arm64` only.

2024-03-12 09:10 UTC, nohant commented
yep I was undecided to which use of the two, better if it works with ARCH

2024-03-12 13:45 UTC, tonyo commented
Looks like ARG is not needed; also added TARGETPLATFORM, should be good now.

2024-03-12 13:46 UTC, merged

2024-03-12 16:59 UTC, nohant commented
super good work, thank you mate